// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1twNAVLHmbNdq9ZfbmpCDlr7lLT5qz0',
    appId: '1:240932160893:web:789048e0326575ebe37814',
    messagingSenderId: '240932160893',
    projectId: 'chat-app-9d76e',
    authDomain: 'chat-app-9d76e.firebaseapp.com',
    storageBucket: 'chat-app-9d76e.appspot.com',
    measurementId: 'G-RXM9F2CEDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrLKY4n_DamrLJccWtQ-fMcOxBF5X5vs',
    appId: '1:240932160893:android:0b2f5917d2a135f8e37814',
    messagingSenderId: '240932160893',
    projectId: 'chat-app-9d76e',
    storageBucket: 'chat-app-9d76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhz-2BxtD074APSWhKotYkKhY_U9DVfU',
    appId: '1:240932160893:ios:a5773855ae9bc60ee37814',
    messagingSenderId: '240932160893',
    projectId: 'chat-app-9d76e',
    storageBucket: 'chat-app-9d76e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKhz-2BxtD074APSWhKotYkKhY_U9DVfU',
    appId: '1:240932160893:ios:976ca47de375db9ee37814',
    messagingSenderId: '240932160893',
    projectId: 'chat-app-9d76e',
    storageBucket: 'chat-app-9d76e.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
